package com.eqt.ssc.web;

import org.restlet.Restlet;
import org.restlet.resource.Get;
import org.restlet.resource.ServerResource;
import org.restlet.routing.Router;

public class StatServerResource extends ServerResource {

	public static class Stat {
		String name;

		public Stat() {
		}

		public Stat(String name) {
			this.name = name;
		}

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}
	}

	private Stat s = new Stat("testy");

	@Get
	Stat getStat() {
		return s;
	}

//	@Override
//	public Restlet createInboundRoot() {
//		Router router = new Router(getContext());
//
//		// Serve the files generated by the GWT compilation step.
//		router.attachDefault(new Directory(getContext(), "war:///"));
//		router.attach("/contacts/123", ContactServerResource.class);
//
//		return router;
//	}

}
